name: Create HTML files for students

on:
    push:
        branches:
            - main

jobs:
    create-student-files:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Create HTML files for each student
              run: |
                  mkdir -p source
                  for student in aya omran bareah lara omar rayan; do
                    echo "<!DOCTYPE html>" > source/$student.html
                    echo "<html>" >> source/$student.html
                    echo "  <body>" >> source/$student.html
                    echo "    hello" >> source/$student.html
                    echo "  </body>" >> source/$student.html
                    echo "</html>" >> source/$student.html
                  done

            - name: Commit and push files
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"
                  git add source/
                  git commit -m "Automatically created student files"
                  git push
